from flask import Flask, render_template, request, redirect, session
from datetime import timedelta
import os, json, threading, cv2, pygame, torch, webbrowser
import numpy as np

# === CLASSIFIER IMPORTS (no YOLO) ===
from torchvision import transforms, models
from PIL import Image

# ----------------- App Config -----------------
app = Flask(__name__)
app.secret_key = 'your_secret_key'
app.permanent_session_lifetime = timedelta(days=30)

# Folders & files
UPLOAD_FOLDER = "uploads"
USER_FILE = "users.json"
LABELS_FILE = "labels.txt"                 # one label per line (generated by training)
CLASSIFIER_WEIGHTS = "classifier_model.pth"  # saved by training script
METADATA_FILE = "metadata.json"            # optional per-label info/buy/link

os.makedirs(UPLOAD_FOLDER, exist_ok=True)


# ===============================================================
#                          AUTH ROUTES
# ===============================================================
def load_users():
    if not os.path.exists(USER_FILE):
        return {}
    with open(USER_FILE, 'r') as f:
        return json.load(f)

def save_users(users):
    with open(USER_FILE, 'w') as f:
        json.dump(users, f)

@app.route('/')
def home():
    if 'user' in session:
        return redirect('/launcher')
    return redirect('/login')

@app.route('/login', methods=['GET', 'POST'])
def login():
    users = load_users()
    if 'user' in session:
        return redirect('/launcher')
    if request.method == 'POST':
        user = request.form['username']
        pwd = request.form['password']
        if users.get(user) == pwd:
            session['user'] = user
            session.permanent = True
            return redirect('/launcher')
        else:
            return "Invalid credentials. <a href='/login'>Try again</a>"
    return render_template("login.html")

@app.route('/register', methods=['GET', 'POST'])
def register():
    users = load_users()
    if 'user' in session:
        return redirect('/launcher')
    if request.method == 'POST':
        user = request.form['username']
        pwd = request.form['password']
        import re
        pwd_pattern = re.compile(r'^(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$')
        if not pwd_pattern.match(pwd):
            return ("Password must be at least 8 characters long and include at least "
                    "one uppercase letter, one number, and one special character. "
                    "<a href='/register'>Try again</a>")
        if user in users:
            return "Username already exists. <a href='/register'>Try again</a>"
        users[user] = pwd
        save_users(users)
        return "Registration successful! <a href='/login'>Login now</a>"
    return render_template("register.html")

@app.route('/launcher')
def launcher():
    if 'user' not in session:
        return redirect('/login')
    return render_template("launcher.html")

@app.route('/logout')
def logout():
    session.pop('user', None)
    return redirect('/login')


# ===============================================================
#                       HELPERS / LOADERS
# ===============================================================
def load_labels():
    if not os.path.exists(LABELS_FILE):
        raise FileNotFoundError(f"'{LABELS_FILE}' not found. Run your training script to generate it.")
    with open(LABELS_FILE, "r", encoding="utf-8") as f:
        labels = [ln.strip() for ln in f.readlines() if ln.strip()]
    if not labels:
        raise ValueError("labels.txt is empty. Add at least one class label.")
    return labels

def load_metadata():
    if os.path.exists(METADATA_FILE):
        try:
            with open(METADATA_FILE, "r", encoding="utf-8") as f:
                data = json.load(f)
                if isinstance(data, dict):
                    return data
        except Exception as e:
            print(f"⚠️ Failed to read {METADATA_FILE}: {e}")
    return {}

def get_metadata(label, fallback_query=None):
    meta = _METADATA.get(label)
    if meta and isinstance(meta, dict):
        info = meta.get("info") or f"Info about {label}"
        link = meta.get("link") or f"https://www.google.com/search?q={label}"
        buy  = meta.get("buy")  or f"https://www.amazon.in/s?k={label}"
        return {"info": info, "link": link, "buy": buy}
    q = fallback_query or label
    return {
        "info": f"Info about {label}",
        "link": f"https://www.google.com/search?q={q}",
        "buy":  f"https://www.amazon.in/s?k={q}"
    }

def load_classifier_flexible(labels):
    """
    Build a ResNet18 with head size = len(labels), then load weights.
    If the checkpoint head shape differs, we load matching layers and keep the new head.
    """
    num_classes = len(labels)
    model = models.resnet18(weights="IMAGENET1K_V1")
    model.fc = torch.nn.Linear(model.fc.in_features, num_classes)

    if not os.path.exists(CLASSIFIER_WEIGHTS):
        raise FileNotFoundError(f"'{CLASSIFIER_WEIGHTS}' not found. Train your classifier and place it here.")

    ckpt = torch.load(CLASSIFIER_WEIGHTS, map_location="cpu")
    state_dict = ckpt.get("state_dict", ckpt)
    cleaned = {}
    for k, v in state_dict.items():
        if k.startswith("model."):
            cleaned[k[6:]] = v
        elif k.startswith("module."):
            cleaned[k[7:]] = v
        else:
            cleaned[k] = v

    model_sd = model.state_dict()
    filtered, skipped = {}, []
    for k, v in cleaned.items():
        if k in model_sd and model_sd[k].shape == v.shape:
            filtered[k] = v
        else:
            skipped.append(k)
    if skipped:
        print(f"ℹ️ Skipping incompatible keys: {', '.join(skipped)}")

    model.load_state_dict(filtered, strict=False)
    model.eval()
    return model

def init_classifier_only():
    labels = load_labels()
    classifier = load_classifier_flexible(labels)
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406],
                             [0.229, 0.224, 0.225])
    ])
    print(f"✅ Classifier initialized with {len(labels)} labels.")
    return classifier, transform, labels


# ===============================================================
#                 MAIN CLASSIFICATION (Click to classify)
# ===============================================================
def run_clickvision(mode, video_path=None):
    print("\n=== ClickVision Startup (Classifier Only) ===")
    pygame.init()

    # Camera / video
    cap = cv2.VideoCapture(0 if mode != 'video' else video_path)
    if not cap.isOpened():
        print("❌ Error: Cannot open camera or video.")
        return

    ret, frame = cap.read()
    if not ret:
        print("❌ Error: Cannot read initial frame.")
        return

    H, W = frame.shape[:2]
    screen = pygame.display.set_mode((W, H))
    pygame.display.set_caption("ClickVision - Classification")

    classifier, tfm, class_labels = init_classifier_only()
    font = pygame.font.SysFont("Arial", 20)
    clock = pygame.time.Clock()

    last_result = None        # dict: {name, conf, meta}
    buy_button = None
    info_button = None

    def classify_center(frame_bgr):
        """Crop a centered square region (~40% of min(H,W)) and classify it."""
        h, w = frame_bgr.shape[:2]
        side = int(0.4 * min(h, w))
        cx, cy = w // 2, h // 2
        x1 = max(0, cx - side // 2)
        y1 = max(0, cy - side // 2)
        x2 = min(w, x1 + side)
        y2 = min(h, y1 + side)

        crop = frame_bgr[y1:y2, x1:x2]
        if crop.size == 0:
            return None

        img = cv2.cvtColor(crop, cv2.COLOR_BGR2RGB)
        pil = Image.fromarray(img)
        tensor = tfm(pil).unsqueeze(0)
        with torch.no_grad():
            logits = classifier(tensor)
            probs = torch.softmax(logits, dim=1)[0]
            conf, pred = torch.max(probs, 0)
        label = class_labels[pred.item()]
        meta = get_metadata(label, fallback_query=label)
        return {"name": label, "conf": float(conf.item()), "bbox": (x1, y1, x2 - x1, y2 - y1), "meta": meta}

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        frame = cv2.flip(frame, 1)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                cap.release()
                pygame.quit()
                return

            # Click → classify center
            if event.type == pygame.MOUSEBUTTONDOWN:
                mouse_pos=pygame.mouse.get_pos()

                if buy_button and buy_button.collidepoint(mouse_pos) and last_result:
                    webbrowser.open(last_result["meta"]["buy"])
                    print(f"🛒 Opening Buy Link: {last_result['meta']['buy']}")
                    continue  # <--- DO NOT hide box

    # --- If More Info button is clicked ---
                if info_button and info_button.collidepoint(mouse_pos) and last_result:
                    webbrowser.open(last_result["meta"]["link"])
                    print(f"ℹ️ Opening Info Link: {last_result['meta']['link']}")
                    continue 

                if last_result:
                    last_result=None
                    continue

                last_result = classify_center(frame)
                if last_result:
                    print(f"🎯 Predicted: {last_result['name']} ({last_result['conf']:.2f})")

                # If user clicked buttons
                mouse_pos = pygame.mouse.get_pos()
                if buy_button and buy_button.collidepoint(mouse_pos) and last_result:
                    webbrowser.open(last_result["meta"]["buy"])
                elif info_button and info_button.collidepoint(mouse_pos) and last_result:
                    webbrowser.open(last_result["meta"]["link"])

        # --- Draw video frame ---
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        surface = pygame.surfarray.make_surface(np.rot90(frame_rgb))
        screen.blit(surface, (0, 0))

        # --- Draw center crop box & label if we have a result ---
        buy_button = None
        info_button = None
        if last_result:
            x, y, w, h = last_result["bbox"]
            pygame.draw.rect(screen, (255, 255, 255), (x, y, w, h), 2)
            text = f"{last_result['name'].replace('_',' ').title()} ({last_result['conf']:.2f})"
            label_surface = font.render(text, True, (255, 255, 255))
            screen.blit(label_surface, (x, max(0, y - 22)))

            # Info panel at top-left with polished styling
            panel_w, panel_h = 360, 120
            panel_x, panel_y = 12, 12  # top-left padding
            panel = pygame.Rect(panel_x, panel_y, panel_w, panel_h)

            # Semi-transparent rounded panel surface for a modern look
            panel_surf = pygame.Surface((panel_w, panel_h), pygame.SRCALPHA)
            panel_surf.fill((12, 12, 12, 220))  # dark translucent background
            try:
                pygame.draw.rect(panel_surf, (255, 255, 255), (0, 0, panel_w, panel_h), 2, border_radius=8)
            except TypeError:
                # Older pygame may not support border_radius; fallback to plain rect
                pygame.draw.rect(panel_surf, (255, 255, 255), (0, 0, panel_w, panel_h), 2)
            screen.blit(panel_surf, (panel_x, panel_y))

            # Title with confidence (slightly larger, bold)
            title_font = pygame.font.SysFont("Arial", 18, bold=True)
            subtitle_font = pygame.font.SysFont("Arial", 14)
            title = title_font.render(f"{last_result['name'].replace('_', ' ').title()} ({last_result['conf']:.2f})", True, (245, 245, 245))
            screen.blit(title, (panel.x + 12, panel.y + 8))

            info_txt = subtitle_font.render("Click the buttons below for more info:", True, (200, 200, 200))
            screen.blit(info_txt, (panel.x + 12, panel.y + 36))

            # Buttons: centered horizontally inside the panel, placed near bottom
            def draw_button(xb, yb, wb, hb, textb, icon=None):
                mp = pygame.mouse.get_pos()
                rect = pygame.Rect(xb, yb, wb, hb)
                hovered = rect.collidepoint(mp)

                # Button colors
                base_color = (40, 120, 200) if textb.lower().startswith('buy') else (80, 80, 80)
                hover_color = tuple(min(255, c + 30) for c in base_color)
                fill_color = hover_color if hovered else base_color

                # Draw rounded button
                try:
                    pygame.draw.rect(screen, fill_color, rect, border_radius=6)
                    pygame.draw.rect(screen, (230, 230, 230), rect, 2, border_radius=6)
                except TypeError:
                    pygame.draw.rect(screen, fill_color, rect)
                    pygame.draw.rect(screen, (230, 230, 230), rect, 2)

                # Text (and optional icon)
                ts = font.render(textb, True, (255, 255, 255))
                text_rect = ts.get_rect(center=(xb + wb/2, yb + hb/2))
                screen.blit(ts, text_rect)
                return rect

            btn_w, btn_h = 140, 36
            gap = 12
            total_w = btn_w * 2 + gap
            # Left-align buttons inside the panel (12px left padding)
            start_x = panel.x + 12
            btn_y = panel.y + panel.h - btn_h - 12

            buy_button = draw_button(start_x, btn_y, btn_w, btn_h, "Buy Now")
            info_button = draw_button(start_x + btn_w + gap, btn_y, btn_w, btn_h, "More Info")

        pygame.display.flip()
        clock.tick(30)


# ===============================================================
#                       FLASK LAUNCHER
# ===============================================================
@app.route('/launch', methods=['POST'])
def launch_clickvision():
    if 'user' not in session:
        return redirect('/login')

    print("\n=== Starting ClickVision Launch (Classifier Only) ===")
    mode = request.form.get('mode', 'live')
    video_path = None

    if mode == 'video':
        file = request.files.get('videoFile')
        if file and file.filename:
            video_path = os.path.join(UPLOAD_FOLDER, file.filename)
            file.save(video_path)
            print(f"Video file saved to: {video_path}")

    try:
        thread = threading.Thread(target=run_clickvision, args=(mode, video_path), daemon=True)
        thread.start()
        print("ClickVision thread started successfully")
        return "ClickVision launched. You can close this tab."
    except Exception as e:
        print(f"Error launching ClickVision: {e}")
        return f"Error launching ClickVision: {str(e)}"


# ===============================================================
#                        APP ENTRY POINT
# ===============================================================
if __name__ == '__main__':
    # Preload metadata once for quick access
    _METADATA = load_metadata()
    try:
        webbrowser.open("http://127.0.0.1:5000")
    except:
        pass
    app.run(debug=True, use_reloader=False)
